# Generated by Django 3.2.12 on 2024-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241119_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureandhumiditydata',
            name='timestamp',
            field=models.CharField(max_length=26),
        ),
    ]
